### PR TITLE
fast forward `mas` branch in 3scale repos

### PR DESCRIPTION
**Pull request by eguzki**
TODO:
- [x] Missing Porta and Zync repos

This PR depends on:
- 3scale toolbox: https://github.com/3scale/3scale_toolbox/pull/375
- Apisonator: https://github.com/3scale/apisonator/pull/348
- APIcast: https://github.com/3scale/APIcast/pull/1402
- 3scale operator: https://github.com/3scale/3scale-operator/pull/831
- Apicast operator: https://github.com/3scale/apicast-operator/pull/196

Those PR need to be merged first

### CODE REVIEW

**Comment by jjkiely** [comment]
Looks good to me! Needs to be merged so you can test it anyway

**Comment by eguzki** [comment]
requested your review in the PRs that need to be merged first. 

PS: there is a way to test this from the feature branch. First, a push event hook needs to be added to run it at least one time, then using the `gh` CLI, can be tested

```
gh workflow run fast-forward-mas-branch.yaml --ref fast-forward-mas-branch -f to_branch=test-branch
```

**Comment by eguzki** [comment]
ready for review @jjkiely 

Tried with `gh workflow run fast-forward-mas-branch.yaml --ref fast-forward-mas-branch -f to_branch=test-branch` and seems to work. Only porta workflow failed because the `test-branch` branch did not exist. https://github.com/3scale/porta/actions/runs/5145889047

**Comment by eguzki** [comment]
Is this ok to be merged @jjkiely ?

**Comment by jjkiely** [comment]
sorry Eguzki, didn't get any notifications for those comments, this looks good to go! :)

**Review by jjkiely — APPROVED** [review]

**Pull request merged**
